[book]
authors = ["The Managarm Project"]
language = "en"
multilingual = false
src = "src"
title = "Managarm Handbook"

[output.html]
git-repository-url = "https://github.com/managarm/managarm"
mathjax-support = true
site-url = "/handbook/"

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
